### ISSUE TITLE
[request] ASN funds on ABN

### ISSUE THREAD

**Issue by Woile** [nicwortel/indexfondsenvergelijken.nl#7]
Hello, thanks for this project, it's pretty cool. 

I've been recently investigating the ASN funds, which are registered in the Netherlands, and I'd like to know if it's possible to add them to the website. It would be useful to have an alternative to NT.

ABN at the moment has 2 ASN funds available. I'd like to know if it's possible to add them here to see their performance on ABN.

#### ASN Duurzaam Aandelenfonds (88%)
ISN: NL0014270225
[Website](https://www.asnbank.nl/beleggen/beleggingsrekening/beleggingsfondsen/asn-duurzaam-aandelenfonds.html)
[Factsheet](https://ofs2.finfiles.nl/getDocument/document/index?ClientId=1bd4bf8bbd6816a1581d35dc288996db&DocumentId=2a42951ab6386d478d52db6a0c3c62dde78eedda&GetActive=0&Download=0)

#### ASN Milieu & Water fonds (12%)
ISN: NL0014270233
[Website](https://www.asnbank.nl/beleggen/beleggingsrekening/beleggingsfondsen/asn-milieu-waterfonds.html)
[Factsheet](https://ofs2.finfiles.nl/getDocument/document/index?ClientId=1bd4bf8bbd6816a1581d35dc288996db&DocumentId=0e831965260c6b7d13f085c1136b91d08be32c1c&GetActive=0&Download=0)

Thanks!

**Comment by nicwortel** [comment]
Hi, thanks for your interest in this project! I noticed your blog post referring to this website, I'm happy to see that it's helpful for other people :slightly_smiling_face: 

I have taken a look at the funds you mentioned, but they appear to be actively managed instead of following a global index. The goal of this website is to compare passive index funds and ETFs which allow you to invest in the global stock market against low costs.

According to the ["Essentiële beleggersinformatie" of the ASN Duurzaam Aandelenfonds](https://www.asnbank.nl/web/file?uuid=15d0d5a6-11dd-4d3b-8f66-b88167a59810&owner=6916ad14-918d-4ea8-80ac-f71f0ff1928e&contentid=1678) this fund invests in circa 120 companies which are selected by the fund provider. In comparison, the number of companies invested in by index funds on this website ranges from 900 to over 6000. So this fund provides a lot less diversification than index funds do.
Secondly, with a total expense ratio of 0.85% per year the costs for this fund are much higher than those of all the listed index funds. For example, the Northern Trust World fund has a total expense ratio of 0.15% and the Emerging Market fund has a total expense ratio of 0.25%. While 0.85% (or 1.05% if you include the ABN service fee) may look insignificant, the effect of compounding interest will have a large impact on your return over a longer period.

I couldn't find the number of holdings for the Milieu & Waterfonds fund, but I expect it to be similar to the Duurzaam Aandelenfonds. On top of that, this fund focuses on a specific sector instead of on the global market. Its total expense ratio of 1.2% is even higher than that of the Duurzaam Aandelenfonds.

I'm afraid that because they are not index funds these funds are out of the scope of this website. If I would include them, they would appear at the bottom of the list because the combined costs (0.85% + 0.2% service fee of ABN) would make them much more expensive than any of the index funds.

**Comment by Woile** [comment]
Thanks for the in-depth explanation, I think this is super useful and even answers the question I had. 

I missed the information that they are actively managed, I will stay with NT.

If I find other funds I'll suggest them here, though I may make the same mistake as my dutch is not good in this context.

Thanks again for the website, it's been really helpful 👍🏻
